"""add_qa_tables_v2

Revision ID: 637967eb846a
Revises: f95c7aa11762
Create Date: 2025-10-28 14:24:14.810983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "637967eb846a"
down_revision: Union[str, Sequence[str], None] = "f95c7aa11762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("question_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("context_files", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_question_text"), "questions", ["question_text"], unique=False
    )
    op.create_index(
        op.f("ix_questions_session_id"), "questions", ["session_id"], unique=False
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("answer_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("sources_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("images_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers")
    op.drop_index(op.f("ix_questions_session_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_question_text"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
